export const rooms = [
  {
    id: 1,
    type: "King Bed",
    view: "Airport View",
    size: "36 - 41 sq m",
    description: "Spacious room featuring a king Hyatt Grand Bed, open-plan bathroom, desk, and daybed.",
    image:["/room&suite/room1.jpg","/room&suite/room3.jpg","/room&suite/room4.jpg","/room&suite/room2.jpg"],
  },
  {
    id: 2,
    type: "Twin Beds",
    view: "Suites",
    size: "36 - 41 sq m",
    description: "Spacious room featuring two twin Hyatt Grand Beds, open-plan bathroom, desk, and daybed.",
    image:["/room&suite/room2.jpg","/room&suite/room3.jpg","/room&suite/room4.jpg","/room&suite/room2.jpg"],
  },
    {
    id: 3,
    type: "King Bed",
    view: "View Varies",
    size: "36 - 41 sq m",
    description: "Spacious room featuring a king Hyatt Grand Bed, open-plan bathroom, desk, and daybed.",
    image:["/room&suite/room3.jpg","/room&suite/room3.jpg","/room&suite/room4.jpg","/room&suite/room2.jpg"],
  },
  {
    id: 4,
    type: "Twin Beds",
    view: "City View",
    size: "36 - 41 sq m",
    description: "Spacious room featuring two twin Hyatt Grand Beds, open-plan bathroom, desk, and daybed.",
    image:["/room&suite/room4.jpg","/room&suite/room3.jpg","/room&suite/room4.jpg","/room&suite/room2.jpg"],
  },
    {
    id: 5,
    type: "King Bed",
    view: "Airport View",
    size: "36 - 41 sq m",
    description: "Spacious room featuring a king Hyatt Grand Bed, open-plan bathroom, desk, and daybed.",
    image:["/room&suite/room5.jpg","/room&suite/room3.jpg","/room&suite/room4.jpg","/room&suite/room2.jpg"],
  },
  {
    id: 6,
    type: "Twin Beds",
    view: "View Varies",
    size: "36 - 41 sq m",
    description: "Spacious room featuring two twin Hyatt Grand Beds, open-plan bathroom, desk, and daybed.",
   image:["/room&suite/room6.jpg","/room&suite/room3.jpg","/room&suite/room4.jpg","/room&suite/room2.jpg"],
  },
    {
    id: 7,
    type: "King Bed",
    view: "City View",
    size: "36 - 41 sq m",
    description: "Spacious room featuring a king Hyatt Grand Bed, open-plan bathroom, desk, and daybed.",
   image:["/room&suite/room7.jpg","/room&suite/room3.jpg","/room&suite/room4.jpg","/room&suite/room2.jpg"],
  },
  {
    id: 8,
    type: "Twin Beds",
    view: "Suites",
    size: "36 - 41 sq m",
    description: "Spacious room featuring two twin Hyatt Grand Beds, open-plan bathroom, desk, and daybed.",
    image:["/room&suite/room8.jpg","/room&suite/room3.jpg","/room&suite/room4.jpg","/room&suite/room2.jpg"],
  },
  
];
